
spring:
  application:
    name: hypercube-api-server
  jackson:
    serialization:
      write_dates_as_timestamps: false
  mvc:
    favicon:
      enabled: false

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
  h2:
    console:
      enabled: false
  jpa:
    show-sql: false
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.cache.use_second_level_cache: true
      hibernate.cache.region.factory_class: org.hibernate.cache.jcache.JCacheRegionFactory
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
      hibernate.cache.use_minimal_puts: true
      hibernate.jdbc.batch_size: 500
    open-in-view: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
  liquibase:
    default-schema: public

server:
  port: 9090
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
    min-response-size: 1024

keycloak:
  bearer-only: true
  use-resource-role-mappings: true

# Spring Actuator Endpoints are Disabled by Default
endpoints:
  enabled: false
  jmx:
    enabled: true
  health:
    enabled: true # enable health endpoint for application monitoring
management:
  security:
    roles: ADMIN # only ROLE_ADMIN can see the full health details
    enabled: true
  health:
    diskspace:
      enabled: false # show diskspace health indicator properties
