spring:
  profiles:
    active: dev
  datasource:
    platform: postgresql
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:transmartDev}?currentSchema=public
    username: ${DB_USERNAME:biomart_user}
    password: ${DB_PASSWORD:biomart_user}
    hikari:
      jdbc-url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:transmartDev}?currentSchema=public
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

keycloak:
  auth-server-url: ${KEYCLOAK_SERVER_URL:https://keycloak-dwh-test.thehyve.net}/auth
  realm: ${KEYCLOAK_REALM:transmart-dev}
  resource: ${KEYCLOAK_CLIENT_ID:transmart-client}
