spring:
  profiles:
    active: prod
  datasource:
    platform: postgresql
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:transmart}?currentSchema=public
    username: ${DB_USERNAME:biomart_user}
    password: ${DB_PASSWORD:biomart_user}
    hikari:
      jdbc-url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:transmart}?currentSchema=public
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

keycloak:
  auth-server-url: ${KEYCLOAK_SERVER_URL}/auth
  realm: ${KEYCLOAK_REALM}
  resource: ${KEYCLOAK_CLIENT_ID}
